// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/contact" | "/cookies" | "/gallery" | "/how-it-works" | "/login" | "/privacy" | "/s/[property]" | "/s/[property]/review" | "/security" | "/services" | "/studio" | "/studio/[property]" | "/studio/[property]/plan/[space]" | "/studio/[property]/report" | "/studio/[property]/reservations" | "/studio/[property]/site" | "/studio/[property]/site/preview" | "/t/[property]" | "/t/[property]/[space]" | "/terms" | "/tour" | "/work"
type AppRouteHandlerRoutes = "/llms.txt" | "/robots.txt" | "/sitemap.xml"
type PageRoutes = never
type LayoutRoutes = "/" | "/s/[property]/review" | "/studio"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/contact": {}
  "/cookies": {}
  "/gallery": {}
  "/how-it-works": {}
  "/llms.txt": {}
  "/login": {}
  "/privacy": {}
  "/robots.txt": {}
  "/s/[property]": { "property": string; }
  "/s/[property]/review": { "property": string; }
  "/security": {}
  "/services": {}
  "/sitemap.xml": {}
  "/studio": {}
  "/studio/[property]": { "property": string; }
  "/studio/[property]/plan/[space]": { "property": string; "space": string; }
  "/studio/[property]/report": { "property": string; }
  "/studio/[property]/reservations": { "property": string; }
  "/studio/[property]/site": { "property": string; }
  "/studio/[property]/site/preview": { "property": string; }
  "/t/[property]": { "property": string; }
  "/t/[property]/[space]": { "property": string; "space": string; }
  "/terms": {}
  "/tour": {}
  "/work": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/s/[property]/review": never
  "/studio": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
